/vis/open OGL 1000x400-0+0
/vis/drawVolume
/vis/viewer/set/viewpointThetaPhi 90 0
/vis/viewer/addCutawayPlane 0 0 0 cm -1 0 0
/vis/viewer/zoomTo 2
#/vis/viewer/set/background white
#/vis/viewer/set/lightsVector -0.8 1 0

/vis/scene/add/trajectories
/vis/scene/add/hits
/vis/scene/endOfEventAction accumulate 1000

#/control/execute ../scripts/neutronBg13th_12.mac

# run this when in the OGL window for animation
#/control/loop ../scripts/rotation.mac step 0. 360. 1
